/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personas;

import graficos.Pantalla;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import principal.Main;

/**
 *
 * @author Jona
 */
public class Panel extends javax.swing.JPanel {
    
    private String foto;
    private Persona persona;
    private DefaultTableModel table_model_personas;
    /**
     * Creates new form Panel
     */
   
    public Panel() {
        initComponents();
        //button_eliminar.setVisible(false);
    }
    
    public void setTableModel(DefaultTableModel table_model_personas){
        this.table_model_personas = table_model_personas;
    }
    
    public void refreshTableModel()
    {
        ArrayList<Persona> lista_personas = Repositorio.obtenerTodos();
        while (table_model_personas.getRowCount() > 0) {
            table_model_personas.removeRow(0);
        }
        
        for(Persona p : lista_personas)
        {
            String[] data = {Integer.toString(p.getId()), Integer.toString(p.getDocumento()), p.getNombre(), p.getTelefono(), p.getEmail(), p.getLugar_nacimiento()};
            table_model_personas.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_documento = new javax.swing.JLabel();
        text_documento = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        button_guardar = new javax.swing.JButton();
        button_buscar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();

        label_documento.setText("Documento");

        text_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_documentoActionPerformed(evt);
            }
        });

        label_nombre.setText("Nombre");

        label_email.setText("Email");

        button_guardar.setText("Guardar");
        button_guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardarActionPerformed(evt);
            }
        });

        button_buscar.setText("Buscar");
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre)
                            .addComponent(label_email)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label_documento)
                                .addGap(18, 18, 18)
                                .addComponent(text_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(button_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_buscar)
                .addGap(18, 18, 18)
                .addComponent(button_cancelar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_documento)
                    .addComponent(text_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_guardar)
                    .addComponent(button_cancelar)
                    .addComponent(button_buscar))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_documentoActionPerformed

    private void button_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardarActionPerformed
       
        if( text_documento.getText().isEmpty() ||
            text_nombre.getText().isEmpty() ||
            text_email.getText().isEmpty() 
            
        ){
            JOptionPane.showMessageDialog(this, "Por favor diligencie todo el formulario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            switch(evt.getActionCommand())
            {
                case "Guardar":
                    persona = Persona.crear(0, Integer.parseInt(text_documento.getText()), text_nombre.getText(),  text_email.getText());
                    Repositorio.crear(persona);
                    JOptionPane.showMessageDialog(this, "Persona creada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                break;
                case "Editar":
                    persona.setDocumento(Integer.parseInt(text_documento.getText()));
                    persona.setNombre(text_nombre.getText());
                    //persona.setTelefono(text_telefono.getText(false));
                    persona.setEmail(text_email.getText());
                    //persona.setLugar_nacimiento(lugar_nacimiento.getText(false));
                    Repositorio.editar(persona);
                    JOptionPane.showMessageDialog(this, "Persona actualizada satisfactoriamente", "Bien", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            
            this.refreshTableModel();
            this.resetPersona();
                
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
        }
    }//GEN-LAST:event_button_guardarActionPerformed

    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed
        String documento = JOptionPane.showInputDialog(this, "Número de documento");
        if(!documento.isEmpty()){
            persona = Repositorio.buscar(documento);
            if(persona != null)
            {
                popularPersona(persona);
            }
        }
    }//GEN-LAST:event_button_buscarActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        resetPersona();
    }//GEN-LAST:event_button_cancelarActionPerformed
    
    private void resetForm() {
        text_documento.setText("");
        text_nombre.setText("");
        text_email.setText("");
        
    }
    
    private void resetPersona() {
        persona.setId(0);
        persona.setDocumento(0);
        persona.setEmail("");
        persona.setNombre("");
        persona.setTelefono("");
        persona.setLugar_nacimiento("");
        popularPersona(persona);
    }
    
    private void popularPersona(Persona persona) {
        text_documento.setText(Integer.toString(persona.getDocumento()));
        text_nombre.setText(persona.getNombre());
        text_email.setText(persona.getEmail());
        
        
        if(persona.getId() != 0){
            
            button_guardar.setActionCommand("Editar");
        } else {
            
            button_guardar.setActionCommand("Guardar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_buscar;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_guardar;
    private javax.swing.JLabel label_documento;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField text_documento;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_nombre;
    // End of variables declaration//GEN-END:variables
}
